//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  Name,
        /// OBJECT_DEFINITION(object_id) AS Definition, is_not_trusted as IsNoCheck
        /// FROM    sys.Check_constraints
        ///WHERE OBJECT_SCHEMA_NAME(parent_object_id) = &apos;{1}&apos; and OBJECT_NAME(parent_object_id) = &apos;{0}&apos;.
        /// </summary>
        public static string CheckConstraintQuery {
            get {
                return ResourceManager.GetString("CheckConstraintQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name AS Name FROM sys.databases.
        /// </summary>
        public static string DatabaseQuery {
            get {
                return ResourceManager.GetString("DatabaseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///OBJECT_NAME(default_object_id) AS Name ,
        ///c.Name AS ColumnName ,
        ///OBJECT_DEFINITION(default_object_id) AS DefaultValue
        ///FROM    sys.Tables t
        ///INNER JOIN sys.columns c ON t.object_id = c.object_id
        ///WHERE    default_object_id &lt;&gt; 0 and t.name = &apos;{0}&apos; and SCHEMA_NAME(t.schema_id) = &apos;{1}&apos;.
        /// </summary>
        public static string DefaultConstraintQuery {
            get {
                return ResourceManager.GetString("DefaultConstraintQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  f.name AS Name, 
        ///COL_NAME(fc.parent_object_id, fc.parent_column_id) AS ColumnName,
        ///OBJECT_NAME(f.referenced_object_id) AS ReferenceTableName,
        ///OBJECT_SCHEMA_NAME(f.referenced_object_id) AS ReferencedSchema,  
        ///COL_NAME(fc.referenced_object_id, fc.referenced_column_id) AS ReferenceColumnName, 
        ///f.is_not_trusted AS IsNocheck into #Temp 
        ///FROM sys.foreign_keys AS f 
        ///INNER JOIN sys.foreign_key_columns AS fc ON f.OBJECT_ID = fc.constraint_object_id 
        ///INNER JOIN sys.objects AS o ON o.OBJECT_ID = fc.ref [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForeignKeyQuery {
            get {
                return ResourceManager.GetString("ForeignKeyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SPECIFIC_NAME AS Name, 
        ///ROUTINE_DEFINITION AS Definition,
        ///stuff 
        ///((SELECT DISTINCT N&apos;,&apos; + o.name, &apos;(&apos;+ o.type_desc + &apos;)&apos;
        ///FROM sys.dm_sql_referenced_entities (&apos;{0}&apos; +&apos;.&apos;+ isr.SPECIFIC_NAME, &apos;OBJECT&apos;) AS ref
        ///JOIN sys.objects AS o ON ref.referenced_id = o.[object_id]
        ///WHERE o.[type] IN (&apos;U&apos;, &apos;V&apos;)
        ///for xml path(&apos;&apos;),type).value(&apos;.&apos;,&apos;nvarchar(max)&apos;), 1,1,&apos;&apos; ) AS Tables
        ///FROM information_schema.routines AS isr
        ///WHERE routine_type = &apos;FUNCTION&apos; 
        ///and Left(Routine_Name, 3) NOT IN (&apos;sp_&apos;, &apos;xp_&apos;, &apos;ms_&apos;)
        ///an [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FunctionQuery {
            get {
                return ResourceManager.GetString("FunctionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ind.name AS Name, col.name as ColumnName, ind.is_unique as IsUnique, ind.index_id, ind.type_desc as Type 
        ///INTO #Temp 
        ///FROM sys.indexes ind 
        ///INNER JOIN sys.index_columns ic ON  ind.object_id = ic.object_id and ind.index_id = ic.index_id 
        ///INNER JOIN sys.tables t ON ind.object_id = t.object_id 
        ///INNER JOIN sys.columns col ON ic.object_id = col.object_id and ic.column_id = col.column_id 
        ///WHERE ind.is_primary_key = 0 AND ind.is_unique_constraint = 0 AND t.is_ms_shipped = 0 
        ///AND t.name = &apos;{1}&apos; AND O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexQuery {
            get {
                return ResourceManager.GetString("IndexQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name AS Name FROM sys.databases WHERE name = &apos;{0}&apos;.
        /// </summary>
        public static string OneDbQuery {
            get {
                return ResourceManager.GetString("OneDbQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PARAMETER_NAME AS Name,
        ///DATA_TYPE AS TypeName, CHARACTER_MAXIMUM_LENGTH AS MaxLength,
        ///NUMERIC_PRECISION AS Precision,
        ///NUMERIC_PRECISION_RADIX AS PrecisionRadix, 
        ///NUMERIC_SCALE AS Scale
        ///FROM INFORMATION_SCHEMA.PARAMETERS
        ///WHERE Left(SPECIFIC_NAME, 3) NOT IN (&apos;sp_&apos;, &apos;xp_&apos;, &apos;ms_&apos;, &apos;fn_&apos;)
        ///AND SPECIFIC_SCHEMA = &apos;{0}&apos; AND SPECIFIC_NAME = &apos;{1}&apos;.
        /// </summary>
        public static string ParameterQuery {
            get {
                return ResourceManager.GetString("ParameterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.name as Name, COL_NAME(ic.[object_id], ic.column_id) as ColumnName, i.type_desc as &apos;Type&apos;  into #Temp 
        ///FROM sys.indexes AS i 
        ///JOIN sys.index_columns AS ic  ON i.[object_id] = ic.[object_id]  
        ///AND i.index_id = ic.index_id 
        ///WHERE i.is_primary_key = 1 
        ///AND i.[object_id] = object_id(&apos;{0}.{1}&apos;, &apos;U&apos;) 
        ///SELECT DISTINCT #Temp.Name , 
        ///STUFF((SELECT N&apos;,&apos; + ColumnName FROM #Temp AS t2 WHERE t2.Name = #Temp.Name 
        ///for xml path(&apos;&apos;)  ,type  ).value(&apos;.&apos;,&apos;nvarchar(max)&apos;), 1,1,&apos;&apos;) AS ColumnName, Type FROM #Te [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrimaryKeyQuery {
            get {
                return ResourceManager.GetString("PrimaryKeyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SPECIFIC_NAME AS Name, 
        ///ROUTINE_DEFINITION AS Definition,
        ///stuff 
        ///((SELECT DISTINCT N&apos;,&apos; + o.name, &apos;(&apos;+ o.type_desc + &apos;)&apos;
        ///FROM sys.dm_sql_referenced_entities (&apos;{0}&apos; +&apos;.&apos;+ isr.SPECIFIC_NAME, &apos;OBJECT&apos;) AS ref
        ///JOIN sys.objects AS o ON ref.referenced_id = o.[object_id]
        ///WHERE o.[type] IN (&apos;U&apos;, &apos;V&apos;)
        ///for xml path(&apos;&apos;),type).value(&apos;.&apos;,&apos;nvarchar(max)&apos;), 1,1,&apos;&apos; ) AS Tables
        ///FROM information_schema.routines AS isr
        ///WHERE routine_type = &apos;PROCEDURE&apos; 
        ///and Left(Routine_Name, 3) NOT IN (&apos;sp_&apos;, &apos;xp_&apos;, &apos;ms_&apos;)
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProcedureQuery {
            get {
                return ResourceManager.GetString("ProcedureQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SCHEMA_NAME as Name 
        ///FROM INFORMATION_SCHEMA.SCHEMATA 
        ///WHERE SCHEMA_OWNER = &apos;dbo&apos;.
        /// </summary>
        public static string SchemaQuery {
            get {
                return ResourceManager.GetString("SchemaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.name as Name, tp.name AS Type, c.max_length as MaxLength, c.[precision] AS Precision, c.scale as Scale,
        /// c.is_nullable as IsNullable, c.is_identity AS IsIdentity, c.is_rowguidcol AS IsRowguidCol,
        ///  (SELECT name FROM sys.schemas AS sch WHERE tp.schema_id = sch.schema_id) AS SchemaName 
        ///    , SeedValue = CASE WHEN c.is_identity = 1 THEN IDENTITYPROPERTY(c.[object_id], &apos;SeedValue&apos;) END  
        ///    , IncrementValue = CASE WHEN c.is_identity = 1 THEN IDENTITYPROPERTY(c.[object_id], &apos;IncrementValue&apos;) END   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TableColumnQuery {
            get {
                return ResourceManager.GetString("TableColumnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME AS Name 
        ///FROM INFORMATION_SCHEMA.TABLES
        ///WHERE (TABLE_SCHEMA = &apos;{0}&apos; and TABLE_TYPE = &apos;BASE TABLE&apos;).
        /// </summary>
        public static string TableQuery {
            get {
                return ResourceManager.GetString("TableQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	o.name as Name, sm.definition as Definition
        ///FROM    sys.objects AS o
        ///INNER JOIN sys.sql_modules sm ON o.object_id = sm.OBJECT_ID
        ///WHERE   o.Type = &apos;TR&apos; AND OBJECT_NAME(Parent_object_id) = &apos;{1}&apos; 
        ///AND OBJECT_SCHEMA_NAME(Parent_object_id) = &apos;{0}&apos;.
        /// </summary>
        public static string TriggerQuery {
            get {
                return ResourceManager.GetString("TriggerQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t.name AS Name, ss.name AS SchemaName, max_length as MaxLength, precision AS Precision, scale AS Scale, is_nullable as IsNullable, 
        ///(SELECT name FROM sys.types AS tt WHERE t.system_type_id = tt.user_type_id) AS Type 
        ///FROM sys.types AS t
        ///INNER JOIN sys.schemas as ss ON ss.schema_id = t.schema_id 
        ///WHERE is_user_defined = 1.
        /// </summary>
        public static string TypeQuery {
            get {
                return ResourceManager.GetString("TypeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [{0}].
        /// </summary>
        public static string UseDbQuery {
            get {
                return ResourceManager.GetString("UseDbQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME AS Name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = &apos;{0}&apos; AND TABLE_SCHEMA = &apos;{1}&apos;.
        /// </summary>
        public static string ViewColumnQuery {
            get {
                return ResourceManager.GetString("ViewColumnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT so.name as Name, sm.definition as Definition, stuff 
        ///((SELECT DISTINCT N&apos;,&apos;+ isc.TABLE_NAME + N&apos;(&apos;+ (SELECT TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES
        ///WHERE TABLE_NAME = isc.TABLE_NAME
        ///) +N&apos;)&apos; 
        ///FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE as isc where isc.VIEW_NAME = so.name 
        ///for xml path(&apos;&apos;)  ,type  ).value(&apos;.&apos;,&apos;nvarchar(max)&apos;), 1,1,&apos;&apos;)
        ///as Tables 
        ///FROM sys.objects AS so
        ///INNER JOIN sys.schemas AS ss ON so.schema_id = ss.schema_id
        ///INNER JOIN sys.sql_modules AS sm ON so.object_id = sm.OBJECT_ID
        ///W [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ViewQuery {
            get {
                return ResourceManager.GetString("ViewQuery", resourceCulture);
            }
        }
    }
}
